# -*- coding: utf-8 -*-
"""Ejemplo 3 - Análisis Bivariado de Datos (CoderHouse).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Grpke6NIXKqSEYvpcsahS98qXvHJNUPD
"""

import pandas as pd
pokemon = pd.read_csv("C:/Users/Layla/Desktop/Docencia/Coder House/Materiales complementarios/Mod 4 - Data Science/4. Análisis Bivariado/Datos/Pokemon.csv", index_col=0)

#Head del df
pokemon.head()

#Veamos el shape
pokemon.shape

#Totalidad de registros por columnas
pokemon.count()

#Tipo de dato de cada columna
pokemon.dtypes

#Principales medidas estadisticas
pokemon.describe().T

#Scatterplot
pokemon.plot.scatter(x='Attack', y='Defense')

"""Hexplot

Una gráfica hexagonal agrega puntos en el espacio en hexágonos y luego colorea esos hexágonos según los valores dentro de ellos.
"""

pokemon.plot.hexbin(x='Attack', y='Defense', gridsize=15)

#Filtramos la data y realizamos una agrupacion
pokemon_stats_legendary = pokemon.groupby(['Legendary', 'Generation']).mean()[['Attack', 'Defense']]
pokemon_stats_legendary

pokemon_stats_legendary.plot.bar(stacked=True)

#Generamos otro dataset
pokemon_stats_by_generation = pokemon.groupby('Generation').mean()[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]
pokemon_stats_by_generation

pokemon_stats_by_generation.plot.line()