# -*- coding: utf-8 -*-
"""Ejemplo 1 - Análisis Bivariado de Datos (CoderHouse).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WEOQ6Ok2MTtgQNP7mYqCBcsnnOzjo9LF
"""

#Importamos las librerias

# Operaciones Basicas
import numpy as np
import pandas as pd
import pandas_profiling

# Visualizacion de Datos
import matplotlib.pyplot as plt
import seaborn as sns

#Lectura del dataframe
data = pd.read_csv('C:/Users/Layla/Desktop/Docencia/Coder House/Materiales complementarios/Mod 4 - Data Science/4. Análisis Bivariado/Datos/heart.csv')
data.head()

#Veamos el shape
data.shape

#Totalidad de registros por columnas
data.count()

#Tipo de dato de cada columna
data.dtypes

#Tipo de estructura del dataset
type(data)

#Principales medidas estadisticas
data.describe().T

#Data Profiling
profile = pandas_profiling.ProfileReport(data)
profile

#Hagamos un HeatMap del df
plt.rcParams['figure.figsize'] = (20, 15)

sns.heatmap(data.corr(), annot = True, cmap = 'Wistia')
plt.title('Heatmap for the Dataset', fontsize = 20)
plt.show()

# tresbps vs target
plt.rcParams['figure.figsize'] = (12, 9)
sns.boxplot(data['target'], data['trestbps'], palette = 'viridis')
plt.title('Relación entre tresbps y target', fontsize = 20)
plt.show()

"""**tresbps**: presión arterial en reposo, la gráfica bivariada anterior entre tresbps (la presión arterial en reposo de un paciente) y target nos indica si el paciente padece la enfermedad cardíaca o no. La trama sugiere claramente que los pacientes que tienen más probabilidades de no sufrir la enfermedad tienen una presión arterial ligeramente mayor que los pacientes que tienen enfermedades cardíacas."""

# cholestrol vs target
plt.rcParams['figure.figsize'] = (12, 9)
sns.violinplot(data['target'], data['chol'], palette = 'colorblind')
plt.title('Relación entre Cholestrol y Target', fontsize = 20, fontweight = 30)
plt.show()

"""El gráfico bivariado anterior entre los niveles de colesterol y el objetivo, sugiere que los pacientes con probabilidades de sufrir enfermedades cardíacas tienen niveles de colesterol más altos en comparación con los pacientes con el target 0 (que probablemente no padezcan enfermedades cardíacas)."""

# Relacion entre sex and target
sns.boxenplot(data['target'], data['sex'], palette = 'Set3')
plt.title('Relacion entre Sex and target', fontsize = 20, fontweight = 30)
plt.show()

#https://seaborn.pydata.org/generated/seaborn.boxenplot.html

#Age vs chol
sns.scatterplot(x="age", y="chol", data=data)
plt.title('Relacion entre Sex and target', fontsize = 20, fontweight = 30)

"""Efectivamente se observa una relación entre la edad y la variable colesterol de tipo positiva, esto significa que a mayor edad también se ve incrementado el colesterol de las personas."""