# -*- coding: utf-8 -*-
"""Desafío - Supermarket (Completo).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vil75rQjJ_QorpkN2vuWjkT_ulhGQ_pC
"""

#Importamos las librerias
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import pandas_profiling

#Importemos el archivo
df = pd.read_csv('supermarket_sales.csv')

#Head del df
df.head()

#Veamos el shape
df.shape

#Totalidad de registros por columnas
df.count()

#Tipo de dato de cada columna
df.dtypes

#Principales medidas estadisticas
df.describe().T

#Data Profiling
profile = pandas_profiling.ProfileReport(df)

"""Ahora bien, a través del uso del Análisis Bivariado, trataremos de responder una serie de preguntas de negocio.

1. ¿Los ingresos brutos afectan las calificaciones que brindan los clientes?

Podemos usar el diagrama de dispersión para responder a esta pregunta.
"""

sns.scatterplot(df['Rating'], df['gross income'])

"""**Respuesta**: Como puede ver en el gráfico de dispersión no existe una relación entre el ingreso bruto de un cliente y su calificación.

2. ¿Qué rama es la más rentable?
"""

sns.boxplot(x=df['Branch'], y=df['gross income'])

"""**Respuesta**: No hay mucha diferencia en el ingreso bruto por sucursales a un nivel promedio. La sucursal C tiene ingresos ligeramente más altos que A o B. Como se observó anteriormente, aunque la sucursal A tiene ventas ligeramente más altas que el resto, C, es decir, Naypyitaw es la sucursal más rentable en términos de ingresos brutos.

3. ¿Existe alguna relación entre género e ingreso bruto?

De manera similar al análisis anterior, podemos usar un diagrama de caja para responder a esta pregunta.
"""

sns.boxplot(x=df['Gender'], y=df['gross income'])

"""**Respuesta** : El ingreso bruto es similar tanto para hombres como para mujeres, aunque las clientas gastan un poco más en el percentil 75.

4. ¿Qué línea de productos genera más ingresos?
"""

cat = df[["Product line", "gross income"]].groupby(['Product line'], as_index=False).sum().sort_values(by='gross income', ascending=False)

plt.figure(figsize=(10,4))

sns.barplot(x='Product line', y='gross income', data=cat)

"""**Respuesta** : El ingreso bruto es más alto en deportes y viajes."""

